### ISSUE TITLE
whats the difference between FactorizerBlock and FactorizerBlockV2?

### ISSUE THREAD

**Issue by earsonlau** [pashtari/factorizer#1]
V2 use learnable DimWisePosEmbed, while V1 do not?

**Comment by pashtari** [comment]
Hi @earsonlau! `FactorizerBlock` and `SegmentationFactorizer` correspond to the original version that can be used to reproduce the results presented in the [paper](https://arxiv.org/abs/2202.12295). `FactorizerBlockV2` and `SegmentationFactorizerV2` are internal trials related to my attempts at making improvements over the original version of Factorizer and achieving a modified version, i.e., FactorizerV2. This work is still in progress, and I am currently performing ablation experiments to obtain a better config and design for the 2nd version.  FactorizerV2 with major updates and improved results will be released soon🤞, Stay tuned!
